version: "3.9"
services:
  postgres:
    image: postgres:17.2
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
